// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://puumaqtfwdylmlropufy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1dW1hcXRmd2R5bG1scm9wdWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MTg2OTAsImV4cCI6MjA3NjE5NDY5MH0.POTzAOtvcoR3HOqyNQjaAjasGdX3sqsnJbmH93eEE0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);